#!/bin/bash
# Generate configuration file from xcconfig

CONFIG_FILE="${SRCROOT}/DailyQuipAI/Core/GeneratedConfig.swift"

# Get API key from build settings
API_KEY="${GEMINI_API_KEY}"

cat > "${CONFIG_FILE}" << EOF
//
//  GeneratedConfig.swift
//  DailyQuipAI
//
//  Auto-generated from Config.xcconfig
//  DO NOT EDIT THIS FILE MANUALLY
//

import Foundation

enum GeneratedConfig {
    static let geminiAPIKey = "${API_KEY}"
}
EOF

echo "✅ Generated config at: ${CONFIG_FILE}"
